[package]
name = "TodoApi"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
rocket = { version = "0.5.1", features = ["json"] }
sea-orm = { version = "1.1.19", features = ["sqlx-sqlite", "runtime-tokio"] }
